# Generated by Django 4.1.2 on 2022-10-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_description',
            new_name='dep_discription',
        ),
    ]
